---
- name: "alpinehelloworld installation"
  hosts: client
  tasks:
    - name: Remove containers
      docker_container:
        name: "alpinehelloworld"
        image: "banhcanh/helloworld"
        ports: 80:80
        state: absent
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: Create default containers
      docker_container:
        pull: true
        name: "alpinehelloworld"
        image: "banhcanh/helloworld"
        ports: 80:80
      vars:
        ansible_python_interpreter: /usr/bin/python3
    - name: "Allow http connection"
      firewalld:
        service: "http"
        permanent: yes
        immediate: yes
        state: "enabled"
      become: yes
      vars:
        ansible_python_interpreter: /usr/bin/python
...
